name: Publish image to Azure
on:
  push:
    branches: [ "staging" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Minor version for each merge
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.64.0
        env:
          WITH_V: true
          DRY_RUN: true
    
      - name: build docker image for Pages Service
        run: |
          docker build -t silkroadprofessionals.azurecr.io/mra-pages-api:${{ steps.taggerDryRun.outputs.new_tag }} .
        working-directory: ./src

      - name: Publish Pages Service to ACR
        run: |
          docker login silkroadprofessionals.azurecr.io -u silkroadprofessionals -p ${{ secrets.ACR_PASS }}
          docker push silkroadprofessionals.azurecr.io/mra-pages-api:${{ steps.taggerDryRun.outputs.new_tag }}
